version: '3.8'

services:
  postgres:
    image: my-python-project
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: bewise
      POSTGRES_USER: junior
      POSTGRES_PASSWORD: 23102023
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    environment:
      SQLALCHEMY_DATABASE_URI: postgresql://junior:23102023@postgres:5434/bewise  # Изменил порт на 5434

volumes:
  postgres_data:

